export const UPDATE_PROGRESS_BAR = "UPDATE_PROGRESS_BAR";
export const SET_ACTIVE_PROGRESS_BAR = "SET_ACTIVE_PROGRESS_BAR";
export const IS_LOADING_BARS = "IS_LOADING_BARS";
export const ERROR_LOADING_BARS = "ERROR_LOADING_BARS";
export const SUCCESS_LOADING_BARS = "SUCCESS_LOADING_BARS";
